services:

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./db_data/:/data/db/
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: smartrackadmin
      MONGO_INITDB_ROOT_PASSWORD: uX5CHs7yrRMVBDQLASnTewqjg4


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: smartrackadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: uX5CHs7yrRMVBDQLASnTewqjg4
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://smartrackadmin:uX5CHs7yrRMVBDQLASnTewqjg4@mongo:27017/

volumes:
  dbdata6: